[tool.poetry]
authors = ["Lucas Pickering <lucas@lucaspickering.me>"]
description = ""
license = "MIT"
name = "soze-mock-hardware"
version = "0.1.0"

[tool.poetry.dependencies]
xtermcolor = "1.3"

[tool.black]
line-length = 80
py36 = true
